export const codes = [
	"AD",
	"AE",
	"AF",
	"AG",
	"AI",
	"AL",
	"AM",
	"AO",
	"AQ",
	"AR",
	"AS",
	"AT",
	"AU",
	"AW",
	"AX",
	"AZ",
	"BA",
	"BB",
	"BD",
	"BE",
	"BF",
	"BG",
	"BH",
	"BI",
	"BJ",
	"BL",
	"BM",
	"BN",
	"BO",
	"BQ",
	"BR",
	"BS",
	"BT",
	"BV",
	"BW",
	"BY",
	"BZ",
	"CA",
	"CC",
	"CD",
	"CF",
	"CG",
	"CH",
	"CI",
	"CK",
	"CL",
	"CM",
	"CN",
	"CO",
	"CR",
	"CU",
	"CV",
	"CW",
	"CX",
	"CY",
	"CZ",
	"DE",
	"DJ",
	"DK",
	"DM",
	"DO",
	"DZ",
	"EC",
	"EE",
	"EG",
	"EH",
	"ER",
	"ES",
	"ET",
	"FI",
	"FJ",
	"FK",
	"FM",
	"FO",
	"FR",
	"GA",
	"GB",
	"GD",
	"GE",
	"GF",
	"GG",
	"GH",
	"GI",
	"GL",
	"GM",
	"GN",
	"GP",
	"GQ",
	"GR",
	"GS",
	"GT",
	"GU",
	"GW",
	"GY",
	"HK",
	"HM",
	"HN",
	"HR",
	"HT",
	"HU",
	"ID",
	"IE",
	"IL",
	"IM",
	"IN",
	"IO",
	"IQ",
	"IR",
	"IS",
	"IT",
	"JE",
	"JM",
	"JO",
	"JP",
	"KE",
	"KG",
	"KH",
	"KI",
	"KM",
	"KN",
	"KP",
	"KR",
	"KW",
	"KY",
	"KZ",
	"LA",
	"LB",
	"LC",
	"LI",
	"LK",
	"LR",
	"LS",
	"LT",
	"LU",
	"LV",
	"LY",
	"MA",
	"MC",
	"MD",
	"ME",
	"MF",
	"MG",
	"MH",
	"MK",
	"ML",
	"MM",
	"MN",
	"MO",
	"MP",
	"MQ",
	"MR",
	"MS",
	"MT",
	"MU",
	"MV",
	"MW",
	"MX",
	"MY",
	"MZ",
	"NA",
	"NC",
	"NE",
	"NF",
	"NG",
	"NI",
	"NL",
	"NO",
	"NP",
	"NR",
	"NU",
	"NZ",
	"OM",
	"PA",
	"PE",
	"PF",
	"PG",
	"PH",
	"PK",
	"PL",
	"PM",
	"PN",
	"PR",
	"PS",
	"PT",
	"PW",
	"PY",
	"QA",
	"RE",
	"RO",
	"RS",
	"RU",
	"RW",
	"SA",
	"SB",
	"SC",
	"SD",
	"SE",
	"SG",
	"SH",
	"SI",
	"SJ",
	"SK",
	"SL",
	"SM",
	"SN",
	"SO",
	"SR",
	"SS",
	"ST",
	"SV",
	"SX",
	"SY",
	"SZ",
	"TC",
	"TD",
	"TF",
	"TG",
	"TH",
	"TJ",
	"TK",
	"TL",
	"TM",
	"TN",
	"TO",
	"TR",
	"TT",
	"TV",
	"TW",
	"TZ",
	"UA",
	"UG",
	"UM",
	"US",
	"UY",
	"UZ",
	"VA",
	"VC",
	"VE",
	"VG",
	"VI",
	"VN",
	"VU",
	"WF",
	"WS",
	"YE",
	"YT",
	"ZA",
	"ZM",
	"ZW",
];
export const adjList = {
	AD: ["FR", "ES"],
	AE: ["OM", "SA"],
	AF: ["CN", "IR", "PK", "TJ", "TM", "UZ"],
	AG: [],
	AI: [],
	AL: ["GR", "ME", "MK", "RS"],
	AM: ["AZ", "GE", "IR", "TR"],
	AO: ["CG", "CD", "NA", "ZM"],
	AQ: [],
	AR: ["BO", "BR", "CL", "PY", "UY"],
	AS: [],
	AT: ["CZ", "DE", "HU", "IT", "LI", "SK", "SI", "CH"],
	AU: [],
	AW: [],
	AX: [],
	AZ: ["AM", "GE", "IR", "RU", "TR"],
	BA: ["HR", "ME", "RS"],
	BB: [],
	BD: ["IN", "MM"],
	BE: ["FR", "DE", "LU", "NL"],
	BF: ["BJ", "CI", "GH", "ML", "NE", "TG"],
	BG: ["GR", "MK", "RO", "RS", "TR"],
	BH: [],
	BI: ["CD", "RW", "TZ"],
	BJ: ["BF", "NE", "NG", "TG"],
	BL: [],
	BM: [],
	BN: ["MY"],
	BO: ["AR", "BR", "CL", "PY", "PE"],
	BQ: [],
	BR: ["AR", "BO", "CO", "GF", "GY", "PY", "PE", "SR", "UY", "VE"],
	BS: [],
	BT: ["CN", "IN"],
	BV: [],
	BW: ["ZA", "ZM", "ZW"],
	BY: ["LV", "LT", "PL", "RU", "UA"],
	BZ: ["GT", "MX"],
	CA: ["US"],
	CC: [],
	CD: ["AO", "BI", "CF", "CG", "RW", "SS", "TZ", "UG", "ZM"],
	CF: ["CM", "TD", "CG", "CD", "SS", "SD"],
	CG: ["AO", "CM", "CF", "CD", "GA"],
	CH: ["AT", "FR", "DE", "IT", "LI"],
	CI: ["BF", "GH", "GN", "LR", "ML"],
	CK: [],
	CL: ["AR", "BO", "PE"],
	CM: ["CF", "TD", "CG", "GQ", "GA", "NG"],
	CN: [
		"AF",
		"BT",
		"HK",
		"IN",
		"KZ",
		"KP",
		"KG",
		"LA",
		"MO",
		"MN",
		"MM",
		"NP",
		"PK",
		"RU",
		"TJ",
		"VN",
	],
	CO: ["BR", "EC", "PA", "PE", "VE"],
	CR: ["NI", "PA"],
	CU: [],
	CV: [],
	CW: [],
	CX: [],
	CY: [],
	CZ: ["AT", "DE", "PL", "SK"],
	DE: ["AT", "BE", "CZ", "DK", "FR", "LU", "NL", "PL", "CH"],
	DJ: ["ER", "ET", "SO"],
	DK: ["DE"],
	DM: [],
	DO: ["HT"],
	DZ: ["LY", "ML", "MR", "MA", "NE", "TN", "EH"],
	EC: ["CO", "PE"],
	EE: ["LV", "RU"],
	EG: ["IL", "LY", "PS", "SD"],
	EH: ["DZ", "MR", "MA"],
	ER: ["DJ", "ET", "SD"],
	ES: ["AD", "FR", "GI", "MA", "PT"],
	ET: ["DJ", "ER", "KE", "SO", "SS", "SD"],
	FI: ["NO", "RU", "SE"],
	FJ: [],
	FK: [],
	FM: [],
	FO: [],
	FR: ["AD", "BE", "DE", "IT", "LU", "MC", "ES", "CH"],
	GA: ["CM", "CG", "GQ"],
	GB: ["IE"],
	GD: [],
	GE: ["AM", "AZ", "RU", "TR"],
	GF: ["BR", "SR"],
	GG: [],
	GH: ["BF", "CI", "TG"],
	GI: ["ES"],
	GL: [],
	GM: ["SN"],
	GN: ["CI", "GW", "LR", "ML", "SN", "SL"],
	GP: [],
	GQ: ["CM", "GA"],
	GR: ["AL", "BG", "MK", "TR"],
	GS: [],
	GT: ["BZ", "SV", "HN", "MX"],
	GU: [],
	GW: ["GN", "SN"],
	GY: ["BR", "SR", "VE"],
	HK: ["CN"],
	HM: [],
	HN: ["SV", "GT", "NI"],
	HR: ["BA", "HU", "ME", "RS", "SI"],
	HT: ["DO"],
	HU: ["AT", "HR", "RO", "RS", "SK", "SI", "UA"],
	ID: ["MY", "PG", "TL"],
	IE: ["GB"],
	IL: ["EG", "JO", "LB", "PS", "SY"],
	IM: [],
	IN: ["BD", "BT", "CN", "MM", "NP", "PK"],
	IO: [],
	IQ: ["IR", "JO", "KW", "SA", "SY", "TR"],
	IR: ["AF", "AM", "AZ", "IQ", "PK", "TR", "TM"],
	IS: [],
	IT: ["AT", "FR", "SM", "SI", "CH", "VA"],
	JE: [],
	JM: [],
	JO: ["IQ", "IL", "PS", "SA", "SY"],
	JP: [],
	KE: ["ET", "SO", "SS", "TZ", "UG"],
	KG: ["CN", "KZ", "TJ", "UZ"],
	KH: ["LA", "TH", "VN"],
	KI: [],
	KM: [],
	KN: [],
	KP: ["CN", "KR", "RU"],
	KR: ["KP"],
	KW: ["IQ", "SA"],
	KY: [],
	KZ: ["CN", "KG", "RU", "TM", "UZ"],
	LA: ["CN", "KH", "MM", "TH", "VN"],
	LB: ["IL", "SY"],
	LC: [],
	LI: ["AT", "CH"],
	LK: [],
	LR: ["CI", "GN", "SL"],
	LS: ["ZA"],
	LT: ["BY", "LV", "PL", "RU"],
	LU: ["BE", "DE", "FR"],
	LV: ["BY", "EE", "LT", "RU"],
	LY: ["DZ", "TD", "EG", "NE", "SD", "TN"],
	MA: ["DZ", "ES", "EH"],
	MC: ["FR"],
	MD: ["RO", "UA"],
	ME: ["AL", "BA", "HR", "RS"],
	MF: ["SX"],
	MG: [],
	MH: [],
	MK: ["AL", "BG", "GR", "RS"],
	ML: ["DZ", "BF", "CI", "GN", "MR", "NE", "SN"],
	MM: ["BD", "CN", "IN", "LA", "TH"],
	MN: ["CN", "RU"],
	MO: ["CN"],
	MP: [],
	MQ: [],
	MR: ["DZ", "ML", "SN", "EH"],
	MS: [],
	MT: [],
	MU: [],
	MV: [],
	MW: ["MZ", "TZ", "ZM"],
	MX: ["BZ", "GT", "US"],
	MY: ["BN", "ID", "TH"],
	MZ: ["MW", "SZ", "ZA", "TZ", "ZM", "ZW"],
	NA: ["AO", "BW", "ZA", "ZM"],
	NC: [],
	NE: ["DZ", "BJ", "BF", "TD", "LY", "ML", "NG"],
	NF: [],
	NG: ["BJ", "CM", "TD", "NE"],
	NI: ["CR", "HN"],
	NL: ["BE", "DE"],
	NO: ["FI", "RU", "SE"],
	NP: ["CN", "IN"],
	NR: [],
	NU: [],
	NZ: [],
	OM: ["AE", "SA", "YE"],
	PA: ["CO", "CR"],
	PE: ["BO", "BR", "CL", "CO", "EC"],
	PF: [],
	PG: ["ID"],
	PH: [],
	PK: ["AF", "CN", "IN", "IR"],
	PL: ["BY", "CZ", "DE", "LT", "RU", "SK", "UA"],
	PM: [],
	PN: [],
	PR: [],
	PS: ["EG", "IL", "JO"],
	PT: ["ES"],
	PW: [],
	PY: ["AR", "BO", "BR"],
	QA: ["SA"],
	RE: [],
	RO: ["BG", "HU", "MD", "RS", "UA"],
	RS: ["AL", "BA", "BG", "HR", "HU", "ME", "MK", "RO"],
	RU: [
		"AZ",
		"BY",
		"CN",
		"EE",
		"FI",
		"GE",
		"KZ",
		"KP",
		"LV",
		"LT",
		"MN",
		"NO",
		"PL",
		"UA",
	],
	RW: ["BI", "CD", "TZ", "UG"],
	SA: ["IQ", "JO", "KW", "OM", "QA", "AE", "YE"],
	SB: [],
	SC: [],
	SD: ["CF", "TD", "EG", "ET", "ER", "LY", "SS"],
	SE: ["FI", "NO"],
	SG: [],
	SH: [],
	SI: ["AT", "HR", "HU", "IT"],
	SJ: [],
	SK: ["AT", "CZ", "HU", "PL", "UA"],
	SL: ["GN", "LR"],
	SM: ["IT"],
	SN: ["GM", "GN", "GW", "ML", "MR"],
	SO: ["DJ", "ET", "KE"],
	SR: ["BR", "GF", "GY"],
	SS: ["CF", "CD", "ET", "KE", "SD", "UG"],
	ST: [],
	SV: ["GT", "HN"],
	SX: ["MF"],
	SY: ["IQ", "IL", "JO", "LB", "TR"],
	SZ: ["MZ", "ZA"],
	TC: [],
	TD: ["CM", "CF", "LY", "NE", "NG", "SD"],
	TF: [],
	TG: ["BJ", "BF", "GH"],
	TH: ["KH", "LA", "MY", "MM"],
	TJ: ["AF", "CN", "KG", "UZ"],
	TK: [],
	TL: ["ID"],
	TM: ["AF", "IR", "KZ", "UZ"],
	TN: ["DZ", "LY"],
	TO: [],
	TR: ["AM", "AZ", "BG", "GE", "GR", "IR", "IQ", "SY"],
	TT: [],
	TV: [],
	TW: [],
	TZ: ["BI", "CD", "KE", "MW", "MZ", "RW", "UG", "ZM"],
	UA: ["BY", "HU", "MD", "PL", "RO", "RU", "SK"],
	UG: ["CD", "KE", "RW", "SS", "TZ"],
	UM: [],
	US: ["CA", "MX"],
	UY: ["AR", "BR"],
	UZ: ["AF", "KZ", "KG", "TJ", "TM"],
	VA: ["IT"],
	VC: [],
	VE: ["BR", "CO", "GY"],
	VG: [],
	VI: [],
	VN: ["KH", "CN", "LA"],
	VU: [],
	WF: [],
	WS: [],
	YE: ["OM", "SA"],
	YT: [],
	ZA: ["BW", "LS", "MZ", "NA", "SZ", "ZW"],
	ZM: ["AO", "BW", "CD", "MW", "MZ", "NA", "TZ", "ZW"],
	ZW: ["BW", "MZ", "ZA", "ZM"],
};
